### ISSUE TITLE
UnsupportedOperationException with play 2.3.7, sbt-np 1.0.0-M5 and jdeb on windows 7

### ISSUE THREAD

**Issue by m-sp** [sbt/sbt-native-packager#499] opened 2015-02-18 14:47 UTC
Hi,

I tried to generate a debian package (`debian:packageBin`) for my play application on windows 7 with the newest version of the native packager. Unfortunately it fails with and unsupportedoperationexception while creating the conffile and the controlfile.

i could also reproduce the exception with a rather simple project: 
https://gist.github.com/m-sp/cfc12f9082cd006ad491

and the stacktrace:

[error] (debian:debianConffilesFile) java.lang.UnsupportedOperationException
[error] (debian:debianControlFile) java.lang.UnsupportedOperationException
[error] Total time: 2 s, completed 18.02.2015 15:38:02
[Debian Example] $ debian:packageBinlas deb
{invalid input}
[Debian Example] $ last debian:debianConffilesFile
java.lang.UnsupportedOperationException
        at java.nio.file.Files.setPosixFilePermissions(Unknown Source)
        at com.typesafe.sbt.packager.chmod$.apply(FileUtil.scala:21)
        at com.typesafe.sbt.packager.debian.DebianPlugin$$anonfun$debianSettings$4.apply(DebianPlugin.scala:163)
        at com.typesafe.sbt.packager.debian.DebianPlugin$$anonfun$debianSettings$4.apply(DebianPlugin.scala:154)
        at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
        at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (debian:debianConffilesFile) java.lang.UnsupportedOperationException

**Comment by muuki88** [comment] 2015-02-18 21:21
Do you use the jdeb extension? Otherwise this is a known issue. Native Debian packaging on windows is  not really supported.

**Comment by m-sp** [comment] 2015-02-18 21:56
Yes i am using the Jdeb extension.

**Comment by muuki88** [comment] 2015-02-19 06:56
Ah, sorry. This is is also a known issue which will be fixed in play 2.4.x. There is already a pr for this. The problem is that the jdeb settings are overridden by play again as the native packager autoplugins aren't used.

**Closed by muuki88** 2015-02-19 06:56 UTC
